// Autogenerated
// ReSharper disable BuiltInTypeReferenceStyle
using System;
using System.Runtime.CompilerServices;
namespace SpanJson
{
    public ref partial struct JsonReader<TSymbol> where TSymbol : struct
    {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public sbyte ReadSByte()
        {
            if (typeof(TSymbol) == typeof(char))
            {
                return ReadUtf16SByte();
            }

            if (typeof(TSymbol) == typeof(byte))
            {
                return ReadUtf8SByte();
            }

            ThrowNotSupportedException();
            return default;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public short ReadInt16()
        {
            if (typeof(TSymbol) == typeof(char))
            {
                return ReadUtf16Int16();
            }

            if (typeof(TSymbol) == typeof(byte))
            {
                return ReadUtf8Int16();
            }

            ThrowNotSupportedException();
            return default;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public int ReadInt32()
        {
            if (typeof(TSymbol) == typeof(char))
            {
                return ReadUtf16Int32();
            }

            if (typeof(TSymbol) == typeof(byte))
            {
                return ReadUtf8Int32();
            }

            ThrowNotSupportedException();
            return default;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public long ReadInt64()
        {
            if (typeof(TSymbol) == typeof(char))
            {
                return ReadUtf16Int64();
            }

            if (typeof(TSymbol) == typeof(byte))
            {
                return ReadUtf8Int64();
            }

            ThrowNotSupportedException();
            return default;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public byte ReadByte()
        {
            if (typeof(TSymbol) == typeof(char))
            {
                return ReadUtf16Byte();
            }

            if (typeof(TSymbol) == typeof(byte))
            {
                return ReadUtf8Byte();
            }

            ThrowNotSupportedException();
            return default;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public ushort ReadUInt16()
        {
            if (typeof(TSymbol) == typeof(char))
            {
                return ReadUtf16UInt16();
            }

            if (typeof(TSymbol) == typeof(byte))
            {
                return ReadUtf8UInt16();
            }

            ThrowNotSupportedException();
            return default;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public uint ReadUInt32()
        {
            if (typeof(TSymbol) == typeof(char))
            {
                return ReadUtf16UInt32();
            }

            if (typeof(TSymbol) == typeof(byte))
            {
                return ReadUtf8UInt32();
            }

            ThrowNotSupportedException();
            return default;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public ulong ReadUInt64()
        {
            if (typeof(TSymbol) == typeof(char))
            {
                return ReadUtf16UInt64();
            }

            if (typeof(TSymbol) == typeof(byte))
            {
                return ReadUtf8UInt64();
            }

            ThrowNotSupportedException();
            return default;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public float ReadSingle()
        {
            if (typeof(TSymbol) == typeof(char))
            {
                return ReadUtf16Single();
            }

            if (typeof(TSymbol) == typeof(byte))
            {
                return ReadUtf8Single();
            }

            ThrowNotSupportedException();
            return default;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public double ReadDouble()
        {
            if (typeof(TSymbol) == typeof(char))
            {
                return ReadUtf16Double();
            }

            if (typeof(TSymbol) == typeof(byte))
            {
                return ReadUtf8Double();
            }

            ThrowNotSupportedException();
            return default;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public decimal ReadDecimal()
        {
            if (typeof(TSymbol) == typeof(char))
            {
                return ReadUtf16Decimal();
            }

            if (typeof(TSymbol) == typeof(byte))
            {
                return ReadUtf8Decimal();
            }

            ThrowNotSupportedException();
            return default;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public bool ReadBoolean()
        {
            if (typeof(TSymbol) == typeof(char))
            {
                return ReadUtf16Boolean();
            }

            if (typeof(TSymbol) == typeof(byte))
            {
                return ReadUtf8Boolean();
            }

            ThrowNotSupportedException();
            return default;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public char ReadChar()
        {
            if (typeof(TSymbol) == typeof(char))
            {
                return ReadUtf16Char();
            }

            if (typeof(TSymbol) == typeof(byte))
            {
                return ReadUtf8Char();
            }

            ThrowNotSupportedException();
            return default;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public DateTime ReadDateTime()
        {
            if (typeof(TSymbol) == typeof(char))
            {
                return ReadUtf16DateTime();
            }

            if (typeof(TSymbol) == typeof(byte))
            {
                return ReadUtf8DateTime();
            }

            ThrowNotSupportedException();
            return default;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public DateTimeOffset ReadDateTimeOffset()
        {
            if (typeof(TSymbol) == typeof(char))
            {
                return ReadUtf16DateTimeOffset();
            }

            if (typeof(TSymbol) == typeof(byte))
            {
                return ReadUtf8DateTimeOffset();
            }

            ThrowNotSupportedException();
            return default;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public TimeSpan ReadTimeSpan()
        {
            if (typeof(TSymbol) == typeof(char))
            {
                return ReadUtf16TimeSpan();
            }

            if (typeof(TSymbol) == typeof(byte))
            {
                return ReadUtf8TimeSpan();
            }

            ThrowNotSupportedException();
            return default;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public DateOnly ReadDateOnly()
        {
            if (typeof(TSymbol) == typeof(char))
            {
                return ReadUtf16DateOnly();
            }

            if (typeof(TSymbol) == typeof(byte))
            {
                return ReadUtf8DateOnly();
            }

            ThrowNotSupportedException();
            return default;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public TimeOnly ReadTimeOnly()
        {
            if (typeof(TSymbol) == typeof(char))
            {
                return ReadUtf16TimeOnly();
            }

            if (typeof(TSymbol) == typeof(byte))
            {
                return ReadUtf8TimeOnly();
            }

            ThrowNotSupportedException();
            return default;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public Guid ReadGuid()
        {
            if (typeof(TSymbol) == typeof(char))
            {
                return ReadUtf16Guid();
            }

            if (typeof(TSymbol) == typeof(byte))
            {
                return ReadUtf8Guid();
            }

            ThrowNotSupportedException();
            return Guid.Empty;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public string ReadString()
        {
            if (typeof(TSymbol) == typeof(char))
            {
                return ReadUtf16String();
            }

            if (typeof(TSymbol) == typeof(byte))
            {
                return ReadUtf8String();
            }

            ThrowNotSupportedException();
            return null;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public Version ReadVersion()
        {
            if (typeof(TSymbol) == typeof(char))
            {
                return ReadUtf16Version();
            }

            if (typeof(TSymbol) == typeof(byte))
            {
                return ReadUtf8Version();
            }

            ThrowNotSupportedException();
            return null;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public Uri ReadUri()
        {
            if (typeof(TSymbol) == typeof(char))
            {
                return ReadUtf16Uri();
            }

            if (typeof(TSymbol) == typeof(byte))
            {
                return ReadUtf8Uri();
            }

            ThrowNotSupportedException();
            return null;
        }
    }
}